language: python
python: 3.7
dist: xenial
sudo: true
before_install:
    - python setup.py install
    - pip install requirements-dev.txt
script:
    - pytest --cov autodb
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always