language: python
python: 3.7
dist: xenial
sudo: true
before_install:
    - pip install coveralls
    - python setup.py install
script:
    - pytest
after_success:
    - coveralls
notifications:
  email:
    recipients:
      - jonathanvusich@gmail.com
    on_success: never
    on_failure: always